name: Generate EPIC snake animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Abdalrahman-Amin
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00D9FF&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-snake-neon.svg?palette=github-dark&color_snake=#39FF14&color_dots=#0D1117,#161B22,#21262D,#30363D,#484F58&background_color=#0D1117
            dist/github-snake-fire.svg?palette=github-dark&color_snake=#FF6B35&color_dots=#FF6B35,#F7931E,#FFD23F,#EE4B2B,#DC143C&background_color=#1a0000
            dist/github-snake-matrix.svg?palette=github-dark&color_snake=#00FF41&color_dots=#003B00,#008F11,#00FF41,#CCFFCC,#FFFFFF&background_color=#000000
            dist/github-snake-ocean.svg?palette=github-dark&color_snake=#00CED1&color_dots=#000080,#0000CD,#1E90FF,#00BFFF,#87CEEB&background_color=#001122
            dist/github-snake-rainbow.svg?palette=github-dark&color_snake=#FF1493&color_dots=#9400D3,#4B0082,#0000FF,#00FF00,#FFFF00,#FF7F00,#FF0000
      
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
